export type CountyName = "Alameda" | "Contra Costa";

export type City = {
  slug: string;
  name: string;
  county: CountyName;
  type: "city" | "town" | "cdp";
  zip: string;
  lat: number;
  lng: number;
  character: string;
  housing: string;
  landmark: string;
  nearby: string[];
};

export const cities: City[] = [
  {
    slug: "hayward",
    name: "Hayward",
    county: "Alameda",
    type: "city",
    zip: "94541",
    lat: 37.6688,
    lng: -122.081,
    character:
      "Hayward sits between the Bay and the hills, with Mission Boulevard, Jackson Street, and the industrial shoreline all inside one working city. It is our home base, so crews already know the short cuts, the steep drives, and the buildings that need a call ahead.",
    housing:
      "Ranch homes from the postwar years, hillside houses above Fairway Park, apartments near downtown, and industrial yards along the western flats.",
    landmark: "downtown Hayward, California State University East Bay, and the Hayward shoreline",
    nearby: ["Castro Valley", "San Lorenzo", "Union City", "San Leandro"],
  },
  {
    slug: "alameda",
    name: "Alameda",
    county: "Alameda",
    type: "city",
    zip: "94501",
    lat: 37.7652,
    lng: -122.2416,
    character:
      "Alameda is an island city of Victorian streets, former naval housing, and a shoreline that still feels like a small town. Parking and ferry-adjacent blocks need a careful truck plan, which we set before we arrive.",
    housing: "Victorian homes, West End cottages, and mid-century units near the former naval air station.",
    landmark: "Park Street, Alameda Beach, and the former Naval Air Station",
    nearby: ["Oakland", "San Leandro", "Emeryville"],
  },
  {
    slug: "albany",
    name: "Albany",
    county: "Alameda",
    type: "city",
    zip: "94706",
    lat: 37.8869,
    lng: -122.2978,
    character:
      "Albany is compact, walkable, and tucked between Berkeley and the water. Driveways are short and streets are calm, so we use a smaller staging plan and keep the visit neighborly.",
    housing: "Craftsman bungalows, small apartments, and hillside homes above Solano Avenue.",
    landmark: "Solano Avenue and Albany Hill",
    nearby: ["Berkeley", "El Cerrito", "Kensington"],
  },
  {
    slug: "berkeley",
    name: "Berkeley",
    county: "Alameda",
    type: "city",
    zip: "94704",
    lat: 37.8715,
    lng: -122.273,
    character:
      "Berkeley mixes university housing, brown-shingle hills, and busy Southside streets. Permit parking, stairs, and shared driveways are normal, and our dispatchers already plan for them.",
    housing: "Brown-shingle homes, apartments near campus, and North Berkeley cottages.",
    landmark: "UC Berkeley, Telegraph Avenue, and the Berkeley Hills",
    nearby: ["Albany", "Oakland", "Emeryville", "Kensington"],
  },
  {
    slug: "dublin",
    name: "Dublin",
    county: "Alameda",
    type: "city",
    zip: "94568",
    lat: 37.7022,
    lng: -121.9358,
    character:
      "Dublin has grown quickly around BART and the I-580 corridor, with new tracts, townhomes, and older pockets near Camp Parks. Garage cleanouts and move-out hauls are a weekly rhythm here.",
    housing: "Newer tract homes, townhouses, and apartments near the Dublin/Pleasanton BART station.",
    landmark: "Dublin Boulevard and the I-580 / I-680 interchange",
    nearby: ["Pleasanton", "San Ramon", "Livermore"],
  },
  {
    slug: "emeryville",
    name: "Emeryville",
    county: "Alameda",
    type: "city",
    zip: "94608",
    lat: 37.8313,
    lng: -122.2852,
    character:
      "Emeryville is small, dense, and full of lofts, biotech offices, and waterfront apartments. Loading docks and garage height limits matter, so we confirm access before the truck leaves Hayward.",
    housing: "Lofts, mid-rise apartments, and a few remaining older cottages.",
    landmark: "the Emeryville marina and the Powell Street corridor",
    nearby: ["Oakland", "Berkeley", "Alameda"],
  },
  {
    slug: "fremont",
    name: "Fremont",
    county: "Alameda",
    type: "city",
    zip: "94536",
    lat: 37.5483,
    lng: -121.9886,
    character:
      "Fremont stretches from the Bay to the Mission hills, with Warm Springs, Niles, and Centerville each feeling like their own town. Same-day trucks cover the distance because we already staff a southern East Bay tech.",
    housing: "Family tract homes, hillside properties in Mission San Jose, and apartments near Warm Springs.",
    landmark: "Mission Peak, Niles Canyon, and the Warm Springs innovation district",
    nearby: ["Newark", "Union City", "Hayward", "Sunol"],
  },
  {
    slug: "livermore",
    name: "Livermore",
    county: "Alameda",
    type: "city",
    zip: "94550",
    lat: 37.6819,
    lng: -121.768,
    character:
      "Livermore sits at the edge of wine country and national lab country, with ranch lots, new subdivisions, and downtown First Street all in one city. Long driveways and barn leftovers are common on our tickets.",
    housing: "Ranch properties, newer subdivisions, and downtown cottages.",
    landmark: "downtown First Street and the Livermore Valley vineyards",
    nearby: ["Pleasanton", "Dublin", "Sunol"],
  },
  {
    slug: "newark",
    name: "Newark",
    county: "Alameda",
    type: "city",
    zip: "94560",
    lat: 37.5297,
    lng: -122.0402,
    character:
      "Newark is a close-knit city between Fremont and the Dumbarton Bridge, with family homes and a growing mixed-use core. We treat it as a regular southern Alameda stop, not a special trip.",
    housing: "Single-family homes, townhouses, and apartments near the NewPark area.",
    landmark: "NewPark Mall and the Newark slough shoreline",
    nearby: ["Fremont", "Union City", "Hayward"],
  },
  {
    slug: "oakland",
    name: "Oakland",
    county: "Alameda",
    type: "city",
    zip: "94612",
    lat: 37.8044,
    lng: -122.2712,
    character:
      "Oakland is many neighborhoods in one city: the hills, the flats, Chinatown, Fruitvale, West Oakland, and the lake. We staff a technician who already works these streets so stairs, security gates, and permit zones do not slow the job.",
    housing: "Craftsman homes, hillside properties, flats apartments, and industrial live-work spaces.",
    landmark: "Lake Merritt, downtown Oakland, and the Oakland hills",
    nearby: ["Alameda", "Berkeley", "Piedmont", "San Leandro", "Emeryville"],
  },
  {
    slug: "piedmont",
    name: "Piedmont",
    county: "Alameda",
    type: "city",
    zip: "94611",
    lat: 37.8244,
    lng: -122.2316,
    character:
      "Piedmont is a residential city in the Oakland hills with winding streets, mature trees, and homes that need a careful carry. We keep trucks off tight corners and walk pieces out when that is kinder to the street.",
    housing: "Large hillside homes, older estates, and quiet residential streets.",
    landmark: "Piedmont Park and the Oakland Avenue ridge",
    nearby: ["Oakland", "Montclair", "Berkeley"],
  },
  {
    slug: "pleasanton",
    name: "Pleasanton",
    county: "Alameda",
    type: "city",
    zip: "94566",
    lat: 37.6624,
    lng: -121.8747,
    character:
      "Pleasanton pairs a historic downtown with master-planned neighborhoods and a busy Hacienda office park. HOA rules and tidy streets mean we stage neatly and leave the curb cleaner than we found it.",
    housing: "Downtown Victorians, family subdivisions, and townhomes near Hacienda.",
    landmark: "Main Street Pleasanton and the Hacienda Business Park",
    nearby: ["Dublin", "Livermore", "San Ramon"],
  },
  {
    slug: "san-leandro",
    name: "San Leandro",
    county: "Alameda",
    type: "city",
    zip: "94577",
    lat: 37.7249,
    lng: -122.1561,
    character:
      "San Leandro sits between Oakland and Hayward with marina neighborhoods, industrial corridors, and long-loved bungalows. It is a core route for our Hayward crews.",
    housing: "Bungalows, marina-area homes, and apartments along East 14th Street.",
    landmark: "the San Leandro Marina and downtown Washington Avenue",
    nearby: ["Oakland", "San Lorenzo", "Hayward", "Alameda"],
  },
  {
    slug: "union-city",
    name: "Union City",
    county: "Alameda",
    type: "city",
    zip: "94587",
    lat: 37.5934,
    lng: -122.0438,
    character:
      "Union City grew between Hayward and Fremont around the Decoto and Alvarado neighborhoods. Family homes, townhouses, and BART-adjacent apartments keep our southern crews busy.",
    housing: "Single-family tracts, townhomes, and apartments near Union City BART.",
    landmark: "Union City BART and the historic Decoto district",
    nearby: ["Hayward", "Fremont", "Newark", "Fairview"],
  },
  {
    slug: "ashland",
    name: "Ashland",
    county: "Alameda",
    type: "cdp",
    zip: "94541",
    lat: 37.6947,
    lng: -122.1139,
    character:
      "Ashland is an unincorporated community between Hayward and San Lorenzo, with East 14th Street as its spine. Residents here get the same Hayward-based response time as the city next door.",
    housing: "Older single-family homes, small apartment courts, and mixed commercial streets.",
    landmark: "East 14th Street and the Ashland corridor",
    nearby: ["Cherryland", "San Lorenzo", "Hayward", "San Leandro"],
  },
  {
    slug: "castro-valley",
    name: "Castro Valley",
    county: "Alameda",
    type: "cdp",
    zip: "94546",
    lat: 37.6941,
    lng: -122.0864,
    character:
      "Castro Valley is a large unincorporated community in the hills above Hayward, with canyon roads, ranch homes, and a village-style downtown. Our crews treat it as a daily zone, not an add-on.",
    housing: "Ranch homes, canyon properties, and apartments near Castro Valley Boulevard.",
    landmark: "Castro Valley Boulevard and Lake Chabot",
    nearby: ["Hayward", "Fairview", "San Lorenzo", "Dublin"],
  },
  {
    slug: "cherryland",
    name: "Cherryland",
    county: "Alameda",
    type: "cdp",
    zip: "94541",
    lat: 37.6791,
    lng: -122.1033,
    character:
      "Cherryland sits between Hayward and Ashland with older lots, mature trees, and a close-in East 14th address. Same-day windows from our Hayward yard are the norm.",
    housing: "Older cottages, small multifamily buildings, and backyard ADUs.",
    landmark: "Meek Estate Park and the Cherryland corridor",
    nearby: ["Hayward", "Ashland", "San Lorenzo"],
  },
  {
    slug: "fairview",
    name: "Fairview",
    county: "Alameda",
    type: "cdp",
    zip: "94542",
    lat: 37.6785,
    lng: -122.046,
    character:
      "Fairview is the hillside community above Hayward, with winding roads, views, and properties that often include sheds or extra lots. We send a truck that can handle the grade.",
    housing: "Hillside single-family homes and larger lots above Hayward.",
    landmark: "the Fairview hills and Five Canyons",
    nearby: ["Hayward", "Castro Valley", "Union City"],
  },
  {
    slug: "san-lorenzo",
    name: "San Lorenzo",
    county: "Alameda",
    type: "cdp",
    zip: "94580",
    lat: 37.681,
    lng: -122.1244,
    character:
      "San Lorenzo is a postwar unincorporated community with tract streets, a village square, and easy access from our Hayward shop. Garage and household cleanouts are the most common calls.",
    housing: "Postwar tract homes, some ADUs, and small apartment clusters.",
    landmark: "San Lorenzo Village and Hesperian Boulevard",
    nearby: ["Hayward", "San Leandro", "Ashland"],
  },
  {
    slug: "sunol",
    name: "Sunol",
    county: "Alameda",
    type: "cdp",
    zip: "94586",
    lat: 37.5944,
    lng: -121.8886,
    character:
      "Sunol is a small canyon community between Fremont and Pleasanton, with ranch properties and a quiet downtown. We plan extra travel time and a truck that can handle rural drives.",
    housing: "Ranch homes, canyon properties, and a small village core.",
    landmark: "Niles Canyon and the Sunol village depot",
    nearby: ["Fremont", "Pleasanton", "Livermore"],
  },
  {
    slug: "antioch",
    name: "Antioch",
    county: "Contra Costa",
    type: "city",
    zip: "94509",
    lat: 38.0049,
    lng: -121.8058,
    character:
      "Antioch sits on the San Joaquin River with older downtown streets and newer hillside tracts. East County families book us for garage cleanouts, move-outs, and construction leftovers from additions.",
    housing: "Older river-adjacent homes, 1990s tracts, and new hillside developments.",
    landmark: "downtown Antioch and the river waterfront",
    nearby: ["Oakley", "Pittsburg", "Brentwood", "Bay Point"],
  },
  {
    slug: "brentwood",
    name: "Brentwood",
    county: "Contra Costa",
    type: "city",
    zip: "94513",
    lat: 37.9319,
    lng: -121.6958,
    character:
      "Brentwood grew from farm town to family city, with orchards still at the edge of new streets. Large garages and backyard projects mean we often send a full truck.",
    housing: "Newer family homes, some ranch remnants, and downtown cottages.",
    landmark: "downtown Brentwood and the surrounding farms",
    nearby: ["Oakley", "Antioch", "Discovery Bay", "Knightsen"],
  },
  {
    slug: "clayton",
    name: "Clayton",
    county: "Contra Costa",
    type: "city",
    zip: "94517",
    lat: 37.941,
    lng: -121.9358,
    character:
      "Clayton is a small city at the foot of Mount Diablo with a walkable downtown and hillside homes. Streets are quiet, so we keep the truck visit short and tidy.",
    housing: "Hillside single-family homes and a compact downtown.",
    landmark: "Clayton’s downtown and Mount Diablo",
    nearby: ["Concord", "Walnut Creek", "Pittsburg"],
  },
  {
    slug: "concord",
    name: "Concord",
    county: "Contra Costa",
    type: "city",
    zip: "94520",
    lat: 37.978,
    lng: -122.0311,
    character:
      "Concord is one of Contra Costa’s largest cities, with Todos Santos Plaza, wide residential streets, and the former naval weapons station lands. We keep a technician based here for central county dispatch.",
    housing: "Ranch homes, apartments near BART, and neighborhoods around Treat Boulevard.",
    landmark: "Todos Santos Plaza and Concord BART",
    nearby: ["Pleasant Hill", "Walnut Creek", "Martinez", "Clayton", "Pacheco"],
  },
  {
    slug: "danville",
    name: "Danville",
    county: "Contra Costa",
    type: "city",
    zip: "94526",
    lat: 37.8216,
    lng: -121.9999,
    character:
      "Danville’s downtown and tree-lined neighborhoods ask for a careful, quiet crew. Estate cleanouts and garage resets are common, and we schedule around school traffic on Hartz Avenue.",
    housing: "Family homes, some larger lots, and downtown-adjacent cottages.",
    landmark: "Hartz Avenue and the Iron Horse Trail",
    nearby: ["Alamo", "San Ramon", "Blackhawk", "Diablo"],
  },
  {
    slug: "el-cerrito",
    name: "El Cerrito",
    county: "Contra Costa",
    type: "city",
    zip: "94530",
    lat: 37.9161,
    lng: -122.3108,
    character:
      "El Cerrito climbs from San Pablo Avenue to the ridge, with BART at the base and hillside streets above. We plan parking and carry distance before we quote.",
    housing: "Hillside homes, mid-century houses, and apartments near San Pablo Avenue.",
    landmark: "El Cerrito Plaza and the ridge above the Bay",
    nearby: ["Richmond", "Albany", "Kensington", "Berkeley"],
  },
  {
    slug: "hercules",
    name: "Hercules",
    county: "Contra Costa",
    type: "city",
    zip: "94547",
    lat: 38.0171,
    lng: -122.2886,
    character:
      "Hercules sits on the waterfront north of Pinole with newer homes, townhouses, and a planned waterfront district. Move-in and move-out hauls are a regular request.",
    housing: "Newer single-family homes, townhouses, and waterfront apartments.",
    landmark: "the Hercules waterfront and Refugio Valley",
    nearby: ["Pinole", "Rodeo", "Richmond"],
  },
  {
    slug: "lafayette",
    name: "Lafayette",
    county: "Contra Costa",
    type: "city",
    zip: "94549",
    lat: 37.8858,
    lng: -122.118,
    character:
      "Lafayette is a Lamorinda city of oak-covered hills, a walkable village, and homes that often include workshops or extra storage. We send crews used to winding drives.",
    housing: "Hillside homes, canyon properties, and a small village core.",
    landmark: "Lafayette Reservoir and downtown Mount Diablo Boulevard",
    nearby: ["Orinda", "Moraga", "Walnut Creek", "Reliez Valley"],
  },
  {
    slug: "martinez",
    name: "Martinez",
    county: "Contra Costa",
    type: "city",
    zip: "94553",
    lat: 38.0194,
    lng: -122.1341,
    character:
      "Martinez is the county seat, with a historic downtown, hillside neighborhoods, and industrial waterfront. Estate cleanouts and downtown apartment turnovers keep our north-county tech busy.",
    housing: "Historic downtown homes, hillside houses, and apartments near the Amtrak station.",
    landmark: "downtown Martinez and the Carquinez Strait",
    nearby: ["Pleasant Hill", "Concord", "Pacheco", "Crockett"],
  },
  {
    slug: "moraga",
    name: "Moraga",
    county: "Contra Costa",
    type: "town",
    zip: "94556",
    lat: 37.8349,
    lng: -122.1297,
    character:
      "Moraga is a quiet Lamorinda town around Saint Mary’s College, with family streets and canyon edges. We keep visits discreet and leave HOA common areas unmarked.",
    housing: "Family homes, townhouses, and a few canyon lots.",
    landmark: "Saint Mary’s College and Moraga Way",
    nearby: ["Lafayette", "Orinda", "Canyon"],
  },
  {
    slug: "oakley",
    name: "Oakley",
    county: "Contra Costa",
    type: "city",
    zip: "94561",
    lat: 37.9974,
    lng: -121.7125,
    character:
      "Oakley sits between Antioch and the Delta, with family tracts and remaining agricultural edges. Large household and yard jobs are typical.",
    housing: "Newer family homes and some older ranch properties.",
    landmark: "downtown Oakley and the Delta edge",
    nearby: ["Antioch", "Brentwood", "Knightsen", "Bethel Island"],
  },
  {
    slug: "orinda",
    name: "Orinda",
    county: "Contra Costa",
    type: "city",
    zip: "94563",
    lat: 37.8771,
    lng: -122.1797,
    character:
      "Orinda’s wooded hills and theater-town center ask for crews who can navigate long private drives. We confirm gate codes and turnaround space before we roll.",
    housing: "Wooded hillside homes and a compact village near BART.",
    landmark: "Orinda Theatre and the Orinda BART village",
    nearby: ["Lafayette", "Moraga", "Berkeley", "Kensington"],
  },
  {
    slug: "pinole",
    name: "Pinole",
    county: "Contra Costa",
    type: "city",
    zip: "94564",
    lat: 38.0044,
    lng: -122.2989,
    character:
      "Pinole sits on the I-80 corridor with a historic Old Town and hillside neighborhoods looking west. Garage and household jobs here often share a truck with Hercules or San Pablo.",
    housing: "Hillside homes, older Old Town houses, and apartments near Appian Way.",
    landmark: "Old Town Pinole and Pinole Valley",
    nearby: ["Hercules", "San Pablo", "El Sobrante", "Richmond"],
  },
  {
    slug: "pittsburg",
    name: "Pittsburg",
    county: "Contra Costa",
    type: "city",
    zip: "94565",
    lat: 38.028,
    lng: -121.8847,
    character:
      "Pittsburg has a marina downtown, industrial shoreline, and growing hillside housing. Commercial debris and household cleanouts both show up on our board.",
    housing: "Older downtown homes, marina apartments, and newer hillside tracts.",
    landmark: "Pittsburg Marina and downtown Railroad Avenue",
    nearby: ["Antioch", "Bay Point", "Concord", "Clayton"],
  },
  {
    slug: "pleasant-hill",
    name: "Pleasant Hill",
    county: "Contra Costa",
    type: "city",
    zip: "94523",
    lat: 37.948,
    lng: -122.0608,
    character:
      "Pleasant Hill is a central county city of tree-lined streets, a downtown around Crescent Drive, and easy freeway access. It is a natural dispatch hub between Walnut Creek and Concord.",
    housing: "Ranch homes, townhouses, and apartments near Contra Costa Boulevard.",
    landmark: "downtown Pleasant Hill and the Iron Horse Trail",
    nearby: ["Walnut Creek", "Concord", "Martinez", "Lafayette"],
  },
  {
    slug: "richmond",
    name: "Richmond",
    county: "Contra Costa",
    type: "city",
    zip: "94804",
    lat: 37.9358,
    lng: -122.3477,
    character:
      "Richmond stretches from the shoreline to the hills, with Point Richmond, the Iron Triangle, and hillside streets each needing a different truck plan. We keep a west-county technician close.",
    housing: "Historic Point Richmond homes, hillside houses, and multifamily buildings in the flats.",
    landmark: "Point Richmond, the Richmond shoreline, and the Kaiser shipyard history",
    nearby: ["San Pablo", "El Cerrito", "El Sobrante", "North Richmond"],
  },
  {
    slug: "san-pablo",
    name: "San Pablo",
    county: "Contra Costa",
    type: "city",
    zip: "94806",
    lat: 37.9621,
    lng: -122.3455,
    character:
      "San Pablo is a compact city surrounded by Richmond, with busy San Pablo Avenue and close-in neighborhoods. Response times from our west-county tech are short.",
    housing: "Smaller lots, multifamily buildings, and older single-family homes.",
    landmark: "San Pablo Avenue and Contra Costa College",
    nearby: ["Richmond", "Pinole", "El Sobrante", "Tara Hills"],
  },
  {
    slug: "san-ramon",
    name: "San Ramon",
    county: "Contra Costa",
    type: "city",
    zip: "94583",
    lat: 37.7799,
    lng: -121.978,
    character:
      "San Ramon is a planned city along I-680 with office parks, family neighborhoods, and Dougherty Valley. HOA rules and clean streets are the norm, and our crews treat them that way.",
    housing: "Master-planned homes, townhouses, and apartments near Bishop Ranch.",
    landmark: "Bishop Ranch and the San Ramon Valley",
    nearby: ["Dublin", "Danville", "Pleasanton", "Blackhawk"],
  },
  {
    slug: "walnut-creek",
    name: "Walnut Creek",
    county: "Contra Costa",
    type: "city",
    zip: "94596",
    lat: 37.9101,
    lng: -122.0652,
    character:
      "Walnut Creek pairs a busy downtown with hillside neighborhoods and Broadway Plaza. Apartment turnovers, office cleanouts, and estate work all come through this city every week.",
    housing: "Downtown condos, hillside homes, and neighborhoods around Rossmoor’s edge.",
    landmark: "downtown Walnut Creek, Broadway Plaza, and the Iron Horse Trail",
    nearby: ["Pleasant Hill", "Lafayette", "Concord", "Alamo"],
  },
  {
    slug: "alamo",
    name: "Alamo",
    county: "Contra Costa",
    type: "cdp",
    zip: "94507",
    lat: 37.8502,
    lng: -122.0322,
    character:
      "Alamo is an unincorporated community of large lots, oaks, and quiet lanes between Walnut Creek and Danville. Estate and garage cleanouts are the usual reason we visit.",
    housing: "Large-lot homes and some older ranch properties.",
    landmark: "the Alamo plaza and Danville Boulevard",
    nearby: ["Danville", "Walnut Creek", "Blackhawk"],
  },
  {
    slug: "bay-point",
    name: "Bay Point",
    county: "Contra Costa",
    type: "cdp",
    zip: "94565",
    lat: 38.0291,
    lng: -121.9616,
    character:
      "Bay Point sits on Suisun Bay west of Pittsburg, with shoreline industry and residential streets inland. Household and commercial hauls share the same routes.",
    housing: "Single-family homes, apartments, and some shoreline-adjacent properties.",
    landmark: "the Bay Point shoreline and Willow Pass",
    nearby: ["Pittsburg", "Concord", "Martinez"],
  },
  {
    slug: "discovery-bay",
    name: "Discovery Bay",
    county: "Contra Costa",
    type: "cdp",
    zip: "94505",
    lat: 37.9085,
    lng: -121.6002,
    character:
      "Discovery Bay is a Delta community of waterfront homes and canals. We plan extra travel time from Hayward and still treat it as a regular East County stop.",
    housing: "Waterfront homes, canalside houses, and some inland tracts.",
    landmark: "the Discovery Bay marina and Delta channels",
    nearby: ["Brentwood", "Byron", "Knightsen"],
  },
  {
    slug: "el-sobrante",
    name: "El Sobrante",
    county: "Contra Costa",
    type: "cdp",
    zip: "94803",
    lat: 37.9771,
    lng: -122.2952,
    character:
      "El Sobrante is a canyon community between Richmond and Pinole, with San Pablo Dam Road as its spine. Hillside drives and older lots are common on our tickets.",
    housing: "Canyon homes, hillside houses, and small commercial stretches.",
    landmark: "San Pablo Dam Road and the El Sobrante hills",
    nearby: ["Richmond", "Pinole", "San Pablo", "Orinda"],
  },
  {
    slug: "kensington",
    name: "Kensington",
    county: "Contra Costa",
    type: "cdp",
    zip: "94708",
    lat: 37.9105,
    lng: -122.2802,
    character:
      "Kensington sits on the ridge above Berkeley and El Cerrito with steep streets and views of the Bay. We send a crew used to stairs and tight parking.",
    housing: "Hillside homes and a few small commercial spots on Arlington Avenue.",
    landmark: "the Arlington and the Kensington ridge",
    nearby: ["Berkeley", "El Cerrito", "Albany", "Orinda"],
  },
  {
    slug: "pacheco",
    name: "Pacheco",
    county: "Contra Costa",
    type: "cdp",
    zip: "94553",
    lat: 37.9838,
    lng: -122.0752,
    character:
      "Pacheco is a small unincorporated community between Martinez and Concord, with older lots and easy freeway access. It is a natural add-on to central county routes.",
    housing: "Older single-family homes and some small multifamily buildings.",
    landmark: "Pacheco Boulevard and the creek corridor",
    nearby: ["Martinez", "Concord", "Pleasant Hill"],
  },
  {
    slug: "rodeo",
    name: "Rodeo",
    county: "Contra Costa",
    type: "cdp",
    zip: "94572",
    lat: 38.0327,
    lng: -122.2669,
    character:
      "Rodeo is a waterfront community on the Carquinez Strait with a historic main street and hillside homes. We pair visits here with Hercules and Crockett when the board allows.",
    housing: "Older town homes, hillside houses, and a compact downtown.",
    landmark: "Parker Avenue and the Rodeo waterfront",
    nearby: ["Hercules", "Crockett", "Pinole"],
  },
  {
    slug: "crockett",
    name: "Crockett",
    county: "Contra Costa",
    type: "cdp",
    zip: "94525",
    lat: 38.0552,
    lng: -122.213,
    character:
      "Crockett is a hillside town under the Carquinez Bridge with steep streets and a strong local identity. We plan a smaller truck and extra carry time.",
    housing: "Hillside cottages and older town homes.",
    landmark: "the Carquinez Bridge and downtown Crockett",
    nearby: ["Port Costa", "Rodeo", "Martinez"],
  },
  {
    slug: "byron",
    name: "Byron",
    county: "Contra Costa",
    type: "cdp",
    zip: "94514",
    lat: 37.9085,
    lng: -121.64,
    character:
      "Byron is a small agricultural community near Discovery Bay and the Altamont edge. Ranch debris, fencing, and household cleanouts are the usual work.",
    housing: "Ranch properties and a small village core.",
    landmark: "Byron Highway and the surrounding farms",
    nearby: ["Discovery Bay", "Brentwood", "Knightsen"],
  },
  {
    slug: "knightsen",
    name: "Knightsen",
    county: "Contra Costa",
    type: "cdp",
    zip: "94548",
    lat: 37.9691,
    lng: -121.6677,
    character:
      "Knightsen remains a rural Delta-edge community with farm roads and larger lots. We treat travel time as part of a fair quote.",
    housing: "Ranch and farm properties.",
    landmark: "Knightsen’s farm roads and Delta edge",
    nearby: ["Oakley", "Brentwood", "Bethel Island"],
  },
  {
    slug: "bethel-island",
    name: "Bethel Island",
    county: "Contra Costa",
    type: "cdp",
    zip: "94511",
    lat: 38.0149,
    lng: -121.6405,
    character:
      "Bethel Island is a Delta island community of docks, levee roads, and weekend homes. Access can be unique; we confirm the address and levee route before we dispatch.",
    housing: "Waterfront and levee-adjacent homes.",
    landmark: "the Bethel Island levee and marina",
    nearby: ["Oakley", "Knightsen", "Discovery Bay"],
  },
  {
    slug: "blackhawk",
    name: "Blackhawk",
    county: "Contra Costa",
    type: "cdp",
    zip: "94506",
    lat: 37.8208,
    lng: -121.9077,
    character:
      "Blackhawk is a gated hillside community east of Danville. Gate codes, HOA rules, and long drives are part of every visit, and we handle them quietly.",
    housing: "Large hillside homes inside planned gates.",
    landmark: "the Blackhawk gates and Mount Diablo views",
    nearby: ["Danville", "San Ramon", "Diablo", "Alamo"],
  },
  {
    slug: "diablo",
    name: "Diablo",
    county: "Contra Costa",
    type: "cdp",
    zip: "94528",
    lat: 37.8349,
    lng: -121.958,
    character:
      "Diablo is a small, private community at the base of Mount Diablo. We schedule around gate access and keep the truck presence brief.",
    housing: "Large private-community homes.",
    landmark: "the Diablo Country Club area and Mount Diablo",
    nearby: ["Danville", "Blackhawk", "Clayton"],
  },
  {
    slug: "reliez-valley",
    name: "Reliez Valley",
    county: "Contra Costa",
    type: "cdp",
    zip: "94549",
    lat: 37.9371,
    lng: -122.1027,
    character:
      "Reliez Valley sits between Lafayette and Pleasant Hill with wooded lanes and larger lots. Estate and yard debris jobs are typical.",
    housing: "Wooded single-family homes on larger lots.",
    landmark: "Reliez Valley Road",
    nearby: ["Lafayette", "Pleasant Hill", "Martinez"],
  },
  {
    slug: "saranap",
    name: "Saranap",
    county: "Contra Costa",
    type: "cdp",
    zip: "94595",
    lat: 37.8871,
    lng: -122.0763,
    character:
      "Saranap is an unincorporated pocket beside Walnut Creek and Lafayette, with older streets and a village feel. Our Walnut Creek tech covers it as a local stop.",
    housing: "Older single-family homes and some small multifamily buildings.",
    landmark: "Olympic Boulevard and the Saranap village edge",
    nearby: ["Walnut Creek", "Lafayette", "Acalanes Ridge"],
  },
  {
    slug: "tara-hills",
    name: "Tara Hills",
    county: "Contra Costa",
    type: "cdp",
    zip: "94806",
    lat: 37.9935,
    lng: -122.3166,
    character:
      "Tara Hills is a hillside residential community near San Pablo and Pinole. Household junk and appliance calls are the usual tickets.",
    housing: "Hillside single-family homes.",
    landmark: "the Tara Hills ridge above San Pablo Bay",
    nearby: ["San Pablo", "Pinole", "Richmond"],
  },
  {
    slug: "north-richmond",
    name: "North Richmond",
    county: "Contra Costa",
    type: "cdp",
    zip: "94801",
    lat: 37.9588,
    lng: -122.3669,
    character:
      "North Richmond sits west of San Pablo and north of central Richmond, with industrial edges and residential blocks. We serve the community with the same care as any other East Bay city.",
    housing: "Single-family homes, multifamily buildings, and industrial-adjacent lots.",
    landmark: "the North Richmond shoreline edge",
    nearby: ["Richmond", "San Pablo", "Bayview"],
  },
  {
    slug: "vine-hill",
    name: "Vine Hill",
    county: "Contra Costa",
    type: "cdp",
    zip: "94553",
    lat: 38.0085,
    lng: -122.096,
    character:
      "Vine Hill is an unincorporated area near Martinez and Pacheco, with mixed residential and light industrial uses. Commercial and household jobs both appear here.",
    housing: "Older homes and industrial-adjacent properties.",
    landmark: "the Vine Hill corridor near Highway 4",
    nearby: ["Martinez", "Pacheco", "Concord"],
  },
  {
    slug: "contra-costa-centre",
    name: "Contra Costa Centre",
    county: "Contra Costa",
    type: "cdp",
    zip: "94523",
    lat: 37.9266,
    lng: -122.0561,
    character:
      "Contra Costa Centre is the office and apartment cluster around Pleasant Hill BART. Tenant turnovers and office cleanouts are the usual reason we are on site.",
    housing: "Apartments, condos, and office-adjacent residences.",
    landmark: "Pleasant Hill / Contra Costa Centre BART",
    nearby: ["Pleasant Hill", "Walnut Creek", "Concord"],
  },
  {
    slug: "acalanes-ridge",
    name: "Acalanes Ridge",
    county: "Contra Costa",
    type: "cdp",
    zip: "94595",
    lat: 37.9047,
    lng: -122.0786,
    character:
      "Acalanes Ridge is a small hillside community between Walnut Creek and Lafayette. Quiet streets and winding drives shape how we stage the truck.",
    housing: "Hillside single-family homes.",
    landmark: "the ridge between Lafayette and Walnut Creek",
    nearby: ["Walnut Creek", "Lafayette", "Saranap"],
  },
  {
    slug: "castle-hill",
    name: "Castle Hill",
    county: "Contra Costa",
    type: "cdp",
    zip: "94595",
    lat: 37.8752,
    lng: -122.038,
    character:
      "Castle Hill is a residential pocket near Walnut Creek and Alamo with hillside streets and larger homes. Estate and furniture jobs are common.",
    housing: "Hillside and ridge homes.",
    landmark: "the Castle Hill ridge above the I-680 corridor",
    nearby: ["Walnut Creek", "Alamo", "Danville"],
  },
  {
    slug: "camino-tassajara",
    name: "Camino Tassajara",
    county: "Contra Costa",
    type: "cdp",
    zip: "94506",
    lat: 37.7885,
    lng: -121.8841,
    character:
      "Camino Tassajara is a growing unincorporated area east of San Ramon and Danville, with newer homes and open-space edges. Garage and construction leftover hauls are typical.",
    housing: "Newer family homes and planned streets.",
    landmark: "Camino Tassajara and the Tassajara Valley edge",
    nearby: ["San Ramon", "Blackhawk", "Livermore"],
  },
  {
    slug: "montalvin-manor",
    name: "Montalvin Manor",
    county: "Contra Costa",
    type: "cdp",
    zip: "94806",
    lat: 37.9955,
    lng: -122.3327,
    character:
      "Montalvin Manor is a small residential community near San Pablo and Tara Hills. Household junk removal here is treated as a local west-county stop.",
    housing: "Modest single-family homes and small lots.",
    landmark: "the Montalvin Manor neighborhood streets",
    nearby: ["San Pablo", "Tara Hills", "Pinole"],
  },
  {
    slug: "bayview",
    name: "Bayview",
    county: "Contra Costa",
    type: "cdp",
    zip: "94806",
    lat: 38.0066,
    lng: -122.353,
    character:
      "Bayview is an unincorporated pocket near San Pablo and North Richmond. We include it so west-county residents are not left off the service map.",
    housing: "Small residential streets near the Bay edge.",
    landmark: "the Bayview pocket near San Pablo Bay",
    nearby: ["San Pablo", "North Richmond", "Richmond"],
  },
  {
    slug: "port-costa",
    name: "Port Costa",
    county: "Contra Costa",
    type: "cdp",
    zip: "94569",
    lat: 38.0463,
    lng: -122.1833,
    character:
      "Port Costa is a tiny Carquinez Strait village with a historic main street and steep access. We schedule these visits with extra care and a truck that fits.",
    housing: "Historic village homes and hillside cottages.",
    landmark: "the Port Costa waterfront and canyon road",
    nearby: ["Crockett", "Martinez"],
  },
  {
    slug: "mountain-view-contra-costa",
    name: "Mountain View",
    county: "Contra Costa",
    type: "cdp",
    zip: "94553",
    lat: 38.0088,
    lng: -122.1177,
    character:
      "Mountain View in Contra Costa County is a small unincorporated community near Martinez, not the Silicon Valley city. We serve it on the same routes as Martinez and Vine Hill.",
    housing: "Small residential streets near Martinez.",
    landmark: "the Mountain View pocket near Martinez",
    nearby: ["Martinez", "Vine Hill", "Pacheco"],
  },
];

export function getCity(slug: string) {
  return cities.find((city) => city.slug === slug);
}

export function citiesByCounty(county: CountyName) {
  return cities.filter((city) => city.county === county);
}

export function findCityByName(name: string) {
  const needle = name.trim().toLowerCase();
  return cities.find((city) => city.name.toLowerCase() === needle || city.slug === needle);
}
